---

- name: Load environment variables and ensure required ones are set
  hosts: localhost
  vars_files:
    - .env.yml  # Make sure this path is correct
  tasks:
    - name: Assert that required variables are loaded
      assert:
        that:
          - GIT_USER_NAME is defined
          - GIT_USER_EMAIL is defined
        msg: | 
          One or more required variables not defined 
          - GIT_USER_NAME 
          - GIT_USER_EMAIL 
          Playbook will stop now.

- name: Example playbook with debugging stop
  hosts: localhost
  vars_files:
    - .env.yml
  tasks:
    - name: Show a debug message for inspection
      debug:
        msg: "This is for debugging purposes var: {{ GIT_USER_NAME }}"

    - name: Pause for manual inspection
      pause:
        prompt: "Press Enter to continue with the next task"


- name: Setup Linux Configurations
  vars_files:
    - .env.yml
  hosts: all
  become: true
  roles:
    - common   # Common tasks for all distros

- name: Setup Fedora-Specific Configurations
  vars_files:
    - .env.yml
  hosts: fedora
  become: true
  roles:
    - fedora


