---
- name: Install keyd package
  become: true
  package:
    name: keyd
    state: present

- name: Ensure /etc/keyd directory exists
  become: true
  file:
    path: /etc/keyd
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create keyd config at "/etc/keyd/default.conf" with my capslock remap config
  become: true
  copy:
    dest: /etc/keyd/default.conf
    content: |
      [ids]
      # This applies to all keyboards
      *

      # Default layer
      [main]
      # Remap CapsLock to Control when held, and use it as a modifier for custom_layer
      capslock = layer(ctrl_layer)

      [ctrl_layer:C]
      # This layer activates when CapsLock is held down
      # CapsLock acts as the Control key
      # You can add additional mappings here if desired

      # Ctrl + ` ACTUALLY toggles CapsLock
      ` = capslock
      # Toggle CapsLock Remap to off
      1 = toggle(basic)

      [basic]
      # If remap is toggled off then CapsLock is CapsLock like normal
      capslock = capslock

      # Default control layer # Remap keys that are pressed when Ctrl is pressed
      [control]
      # Ctrl+1 toggles CapsLock back on
      1 = toggle(basic)
    owner: root
    group: root
    mode: '0644'
    force: true

- name: Enable and start keyd service
  become: true
  systemd:
    name: keyd
    enabled: true
    state: started

