---
# Setup mpd (Music Player Daemon) and Mpris integration for it
- name: Ensure MPD-related files and directories exist
  become: false

  tasks:
    - name: Ensure base directory exists
      file:
        path: /home/{{ ansible_user }}/.config/mpd
        state: directory
        mode: '0755'

    - name: Ensure database file exists
      file:
        path: /home/{{ ansible_user }}/.config/mpd/database
        state: touch
        mode: '0644'

    - name: Ensure log file exists
      file:
        path: /home/{{ ansible_user }}/.config/mpd/log
        state: touch
        mode: '0644'

    - name: Ensure mpd_socket (Unix socket) exists
      file:
        path: /home/{{ ansible_user }}/.config/mpd/mpd_socket
        state: touch
        mode: '0666'

    - name: Ensure playlists directory exists
      file:
        path: /home/{{ ansible_user }}/.config/mpd/playlists
        state: directory
        mode: '0755'

    - name: Ensure state file exists
      file:
        path: /home/{{ ansible_user }}/.config/mpd/state
        state: touch
        mode: '0644'

    - name: Ensure sticker.sql file exists
      file:
        path: /home/{{ ansible_user }}/.config/mpd/sticker.sql
        state: touch
        mode: '0644'

- name: Enable mpd.service at user level
  become: false

  tasks:
    - name: Enable mpd.service for current user - {{ ansible_user }}
      shell: systemctl --user enable mpd.service

- name: Ensure GOPATH bin directory exists
  become: false
  file:
    path: "/home/{{ ansible_user }}/go/bin"
    state: directory
    mode: '0755'

- name: Install mpd-mpris using go install
  become: false
  shell: |
    export PATH="$PATH:/usr/bin"
    export GOPATH="$HOME/go"
    go install github.com/natsukagami/mpd-mpris/cmd/mpd-mpris@latest
  args:
    executable: /bin/bash
  environment:
    GOPATH: "/home/{{ ansible_user }}/go"
  creates: "/home/{{ ansible_user }}/go/bin/mpd-mpris"

- name: Enable mpd-mpris.service at user level
  become: false
  tasks:
    - name: Enable mpd-mpris.service for current user - {{ ansible_user }}
      shell: systemctl --user enable mpd-mpris.service


- name: Install Cargo/Rust package "rmpc" terminal music player ( mpd client )
  become: false
  ansible.builtin.shell: |
    cargo install --git https://github.com/mierak/rmpc --locked
  args:
    creates: "/home/{{ ansible_user }}/.cargo/bin/rmpc"

