---
- name: Install Fedora packages 
  become: true
  package:
    name:
      - jq # Parse json files
      - stow # create symlinks for dotfiles
      - bat # nicer cat utility
      - flatpak
      - git
      - gh # github cli
      - curl
      - neovim
      # Neovim plugin dependencies
      - zip
      - unzip
      - fd-find
      - ripgrep
      - make
      - automake
      - gcc
      - gcc-c++
      - nodejs # For copilot neovim plugin
      - wl-clipboard # clipboard support wayland
      - xclip # clipboard support Xorg X11
      # Others
      - zsh
      - zsh-autosuggestions
      - btop
      - fzf
      - lsd # prettier 'ls' output with icons and colors
      - docker-ce # docker community edition
      - docker-compose-plugin
      - ghostty # Terminal emulator
      - yt-dlp # youtube video downloader
      - btrfs-assistant
      - cargo # Rust programming language package manager
      - golang # golang programming language and package manager
      - code # VScode
      - fastfetch
      - steam
      - vlc
      - mpv
      - brave-browser
      - tftp-server # We are network engineers
      - mullvad-vpn
      - tailscale
      - timeshift
      - sshpass # required for ansible 
      - mpd # Music player daemon for music playing in terminal
      # - mpc # Music player daemon controller for quick control "mpc pause" "mpc play" "mpc stop"
    state: present

- name: Upgrade all packages to the latest version
  become: true
  dnf:
    name: '*'
    state: latest
