---
- name: Install Fedora packages 
  become: true
  package:
    name:
      - jq # Parse json files
      - stow # create symlinks for dotfiles
      - flatpak
      - git
      - gh # github cli
      - curl
      - neovim
      # Neovim plugin dependencies
      - zip
      - unzip
      - fd-find
      - ripgrep
      - make
      - automake
      - gcc
      - gcc-c++
      - nodejs # For copilot neovim plugin
      - wl-clipboard # clipboard support wayland
      - xclip # clipboard support Xorg X11
      # Others
      - zsh
      - zsh-autosuggestions
      - btop
      - fzf
      - docker-ce # docker community edition
      - docker-compose-plugin
      - ghostty # Terminal emulator
      - yt-dlp # youtube video downloader
      - btrfs-assistant
      - cargo # Rust programming language package manager
      - code # VScode
      - fastfetch
      - steam
      - vlc
      - mpv
      - brave-browser
      - mullvad-vpn
      - tailscale
      - timeshift
      - sshpass
    state: present

- name: Upgrade all packages to the latest version
  dnf:
    name: '*'
    state: latest
