---

# - name: Configure Fedora repos
#   become: true
#   tasks:

- name: Ensure dnf-plugins-core is installed
  become: true
  dnf:
    name: dnf-plugins-core
    state: present


 # RPM fusion non-free keys as of May 2025
- name: Import RPM Fusion nonfree GPG key
  become: true
  rpm_key:
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
    state: present
  register: result
  retries: 3
  delay: 5
  until: result is succeeded


 # RPM fusion free keys as of May 2025
- name: Import RPM Fusion free GPG key
  become: true
  rpm_key:
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
    state: present
  register: result
  retries: 3
  delay: 5
  until: result is succeeded

- name: Enable the RPM Fusion nonfree repository (includes nonfree-nvidia)
  become: true
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: Ensure RPM Fusion free repository is present
  become: true
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: Ensure Brave Browser repository is present
  become: true  
  copy:
    dest: /etc/yum.repos.d/brave-browser.repo
    content: |
      [brave-browser]
      name=Brave Browser
      enabled=1
      autorefresh=1
      gpgcheck=1
      gpgkey=https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
      baseurl=https://brave-browser-rpm-release.s3.brave.com/$basearch
    owner: root
    group: root
    mode: '0644'

- name: Ensure Tailscale repository is present
  become: true  
  copy:
    dest: /etc/yum.repos.d/tailscale.repo
    content: |
      [tailscale-stable]
      name=Tailscale stable
      baseurl=https://pkgs.tailscale.com/stable/fedora/$basearch
      enabled=1
      type=rpm
      repo_gpgcheck=1
      gpgcheck=0
      gpgkey=https://pkgs.tailscale.com/stable/fedora/repo.gpg
    owner: root
    group: root
    mode: '0644'

- name: Ensure Microsoft repository is present
  become: true  
  copy:
    dest: /etc/yum.repos.d/microsoft.repo
    content: |
      [packages-microsoft-com-prod]
      name=packages-microsoft-com-prod
      baseurl=https://packages.microsoft.com/yumrepos/microsoft-rhel9.0-prod
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.microsoft.com/keys/microsoft.asc
    owner: root
    group: root
    mode: '0644'

- name: Ensure Sublime Text repository is present
  become: true  
  copy:
    dest: /etc/yum.repos.d/sublime-text.repo
    content: |
      [sublime-text]
      name=Sublime Text - x86_64 - Stable
      baseurl=https://download.sublimetext.com/rpm/stable/x86_64
      enabled=1
      gpgcheck=1
      gpgkey=https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    owner: root
    group: root
    mode: '0644'

- name: Ensure Docker CE repository is present
  become: true  
  copy:
    dest: /etc/yum.repos.d/docker-ce.repo
    content: |
      [docker-ce-stable]
      name=Docker CE Stable - $basearch
      baseurl=https://download.docker.com/linux/fedora/$releasever/$basearch/stable
      enabled=1
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/fedora/gpg

      [docker-ce-stable-debuginfo]
      name=Docker CE Stable - Debuginfo $basearch
      baseurl=https://download.docker.com/linux/fedora/$releasever/debug-$basearch/stable
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/fedora/gpg

      [docker-ce-stable-source]
      name=Docker CE Stable - Sources
      baseurl=https://download.docker.com/linux/fedora/$releasever/source/stable
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/fedora/gpg

      [docker-ce-test]
      name=Docker CE Test - $basearch
      baseurl=https://download.docker.com/linux/fedora/$releasever/$basearch/test
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/fedora/gpg

      [docker-ce-test-debuginfo]
      name=Docker CE Test - Debuginfo $basearch
      baseurl=https://download.docker.com/linux/fedora/$releasever/debug-$basearch/test
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/fedora/gpg

      [docker-ce-test-source]
      name=Docker CE Test - Sources
      baseurl=https://download.docker.com/linux/fedora/$releasever/source/test
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/fedora/gpg

      [docker-ce-nightly]
      name=Docker CE Nightly - $basearch
      baseurl=https://download.docker.com/linux/fedora/$releasever/$basearch/nightly
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/fedora/gpg

      [docker-ce-nightly-debuginfo]
      name=Docker CE Nightly - Debuginfo $basearch
      baseurl=https://download.docker.com/linux/fedora/$releasever/debug-$basearch/nightly
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/fedora/gpg

      [docker-ce-nightly-source]
      name=Docker CE Nightly - Sources
      baseurl=https://download.docker.com/linux/fedora/$releasever/source/nightly
      enabled=0
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/fedora/gpg
    owner: root
    group: root
    mode: '0644'

- name: Ensure Mullvad VPN repository is present
  become: true  
  copy:
    dest: /etc/yum.repos.d/mullvad.repo
    content: |
      [mullvad-stable]
      name=Mullvad VPN
      baseurl=https://repository.mullvad.net/rpm/stable/$basearch
      type=rpm
      enabled=1
      gpgcheck=1
      gpgkey=https://repository.mullvad.net/rpm/mullvad-keyring.asc
    owner: root
    group: root
    mode: '0644'

- name: Ensure Visual Studio Code repository is present
  become: true  
  copy:
    dest: /etc/yum.repos.d/vscode.repo
    content: |
      [VScode]
      name=VScode repo from microsoft
      baseurl=https://packages.microsoft.com/yumrepos/vscode
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.microsoft.com/keys/microsoft.asc
      async=1
    owner: root
    group: root
    mode: '0644'

- name: Add Terra repository
  become: true
  copy:
    dest: "/etc/yum.repos.d/terra.repo"
    content: |
      [terra]
      name=Terra $releasever
      baseurl=https://repos.fyralabs.com/terra$releasever
      type=rpm
      skip_if_unavailable=True
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://repos.fyralabs.com/terra$releasever/key.asc
      enabled=1
      enabled_metadata=1
      metadata_expire=4h
    owner: root
    group: root
    mode: '0644'

- name: Add Repo for 'nushell' package
  become: true
  copy:
    dest: "/etc/yum.repos.d/fury-nushell.repo"
    content: |
      [gemfury-nushell]
      name=Gemfury Nushell Repo
      baseurl=https://yum.fury.io/nushell/
      enabled=1
      gpgcheck=0
      gpgkey=https://yum.fury.io/nushell/gpg.key"
    owner: root
    group: root
    mode: '0644'

# - name: Add Ghostty COPR repo
#   become: true
#   copy:
#     dest: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:pgdev:ghostty.repo
#     content: |
#       [copr:copr.fedorainfracloud.org:pgdev:ghostty]
#       name=Copr repo for ghostty owned by pgdev
#       baseurl=https://download.copr.fedorainfracloud.org/results/pgdev/ghostty/fedora-$releasever-$basearch/
#       type=rpm-md
#       skip_if_unavailable=True
#       gpgcheck=1
#       gpgkey=https://download.copr.fedorainfracloud.org/results/pgdev/ghostty/pubkey.gpg
#       repo_gpgcheck=0
#       enabled=0
#       enabled_metadata=1
#     mode: '0644'

# - name: Add Keyd COPR repo
#   become: true
#   copy:
#     dest: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:alternateved:keyd.repo
#     content: |
#       [copr:copr.fedorainfracloud.org:alternateved:keyd]
#       name=Copr repo for keyd owned by alternateved
#       baseurl=https://download.copr.fedorainfracloud.org/results/alternateved/keyd/fedora-$releasever-$basearch/
#       type=rpm-md
#       skip_if_unavailable=True
#       gpgcheck=1
#       gpgkey=https://download.copr.fedorainfracloud.org/results/alternateved/keyd/pubkey.gpg
#       repo_gpgcheck=0
#       enabled=1
#       enabled_metadata=1
#     mode: '0644'

# - name: Add Lazygit COPR repo
#   become: true
#   copy:
#     dest: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:atim:lazygit.repo
#     content: |
#       [copr:copr.fedorainfracloud.org:atim:lazygit]
#       name=Copr repo for lazygit owned by atim
#       baseurl=https://download.copr.fedorainfracloud.org/results/atim/lazygit/fedora-$releasever-$basearch/
#       type=rpm-md
#       skip_if_unavailable=True
#       gpgcheck=1
#       gpgkey=https://download.copr.fedorainfracloud.org/results/atim/lazygit/pubkey.gpg
#       repo_gpgcheck=0
#       enabled=0
#       enabled_metadata=1
#     mode: '0644'




